### ISSUE TITLE
Question about where contract mapping code lives

### ISSUE THREAD

**Issue by zprobinson** [atsapura/CardManagement#10]
Not really an issue, but there wasn't a discussion forum or I'd have put it there.

I've been reading through your (fantastic) article, I think you bring up a lot of really great ideas.

Curious if you'd be willing to expand on your opinion where the contract mapping code lives in the Domain project.

Normally I've been keeping the contract code purely to the boundaries of the application. My thoughts are that it is the concern of the WebAPI layer to define/maintain the definitions of how the domain aggregates are represented to other systems. Similar to how you've done it in the Data layer. The Data layer is concerned with the representation/mapping of the domain to however it looks when persisted to the database.

Would you argue that the definition of the exposed contract is the concern of the domain? I'm not trying to push one way or the other, just interested in hearing you expand on your thoughts..

**Comment by atsapura** [comment]
Good question!
For most cases I'd say that mapping from domain is the responsibility of the target, since the idea behind domain is that it's a pure model of the business-domain, its only responsibility is to reflect the real set of business rules in code as precisely and concisely as possible. Anything else is a separate problem and therefore normally is better to be addressed separately.

All that being said, practicality first. Your code is supposed to serve you, not the other way around. So it's fine if you have to violate that rule in case if you need to deploy the fix in 30 mins or if the entire project is so small, that it doesn't make a lot of sense to segregate your code in it to the highest degree possible.

**Comment by zprobinson** [comment]
I appreciate your response!

I know there is a problem of over-posting the underlying data in some web applications. But normally that is a problem when you are writing a data-centric application instead of a domain-centric application.

Perhaps once you design your aggregates in a domain-centric manner, the idea of over-posting goes away, cuz the implementation details of the database are abstracted away.

That gives me a bit to think about!
